### PR TITLE
Add precommit hooks running eslint and prettier

### PR DESCRIPTION
**Pull request by maskudo**
This PR aims to standardize and improve code quality by introducing pre-commit hooks for linting and formatting.

## Problem Statement:
I noticed lots of unused variables, incorrect prop names. Similarly, prettier wasn't installed properly resulting in developer's default editor settings for formatting being applied. 
image
image

## Dependencies Added
- Prettier: We had a .prettierrc file but the dependency was not installed properly
- Husky: For pre-commit hooks
- Lint-staged: For applying prettier and eslint checks on staged files before commit

### CODE REVIEW

**Comment by utsavdotdev** [comment]
@maskudo, Thanks for your contribution! Could you apply the suggested changes? After that, it’ll be good to go.

**Comment by maskudo** [comment]
I have applied the suggested changes. 
Furthermore, I have disabled the following rules:
```   
{
    "react-refresh/only-export-components": "off",
    "react/prop-types": "off"
}
```
## Notes 

I have disabled eslint for the docusaurus directory because it uses a mix of commonjs and ecmascript modules which we dont have a clean way of resolving and trying to fix it doesnt feel worth the cost. We could probably have an eslint rule for the docusaurus page only inside its package.json if we need it in the future. 
I'm assuming we would simply be using typescript or jsdocs if we were serious about typing our props so we probably dont need the prop-types rules. 
The 'only export components' rule was previously set to warn which we dont really need. We export some hooks and constants along with some components which are good logical pairing that doesnt really make sense to split just for the sake of it.

**Comment by utsavdotdev** [comment]
Stills logs message are not changed!

**Comment by utsavdotdev** [comment]
Once again @maskudo , Thanks for your contribution

**Pull request merged**
