### PR TITLE
Fix Issue in FAQ Section with Empty Placeholder Boxes by Adding Conditionals (Issue No. #87)

### PR DESCRIPTION
**Pull request by fuyalasmit**
# PR Description

## Description:

- **Problem:** The FAQ section was displaying empty placeholder boxes when there was no FAQ data.
- **Solution:** Added a conditional check to ensure that when the FAQ array is empty or not available, a user-friendly message is displayed instead of the empty boxes.
- **Impact:** The FAQ section now shows relevant content or a helpful message when no FAQs are present, improving the user experience.

## Comparison:

- **Before:**  
  Before

- **After:**  
  After

### CODE REVIEW

**Comment by utsavdotdev** [comment]
For the FAQ section, it’s better to display a default FAQ. I can provide the data—can you implement logic to check if the FAQ data is available from the backend? If it is, display that; otherwise, show the default FAQ.

**Comment by fuyalasmit** [comment]
> For the FAQ section, it’s better to display a default FAQ. I can provide the data—can you implement logic to check if the FAQ data is available from the backend? If it is, display that; otherwise, show the default FAQ.

Sure, I’ll try implementing the logic as suggested. Could you please provide the default FAQ data so I can proceed?

**Comment by utsavdotdev** [comment]
Here you go:
```js
const items = [
  {
    question: 'What is GNOME Nepal?',
    answer: 'GNOME Nepal is an open-source organization focused on promoting collaboration and open-source culture in Nepal.',
  },
  {
    question: 'How can I join this community?',
    answer: 'You can join us by connecting through our Discord!',
  },
  {
    question: 'What is open source?',
    answer: 'Open-source software is software made available under a license that allows users to freely use, study, modify, and share its source code.',
  },
  {
    question: 'Can I contribute to the organization?',
    answer: 'Absolutely, we welcome your contributions!',
  },
  {
    question: 'Are there any exciting events?',
    answer: 'Check out the Events section to stay updated on our upcoming events.',
  },
];
```

**Comment by fuyalasmit** [comment]
Okay, I implemented what you said. I also fixed the Accordian.jsx file since color theme-based color switching wasn't working in mobile view.

See this:

- **Before**
image

- **After**
image

**Comment by fuyalasmit** [comment]
@utsavdotdev can you check it

**Comment by utsavdotdev** [comment]
I just reviewed the PR, and you can check your preview URL here: [https://deploy-preview-88–gnomenepal.netlify.app/](https://deploy-preview-88--gnomenepal.netlify.app/).

The FAQs aren’t showing because you tested it without calling the API, as the API isn’t public —which is fine. To fix this, update the condition like this:

```js
const faqs = data?.length > 0 ? data : items;
```

**Comment by fuyalasmit** [comment]
@utsavdotdev 

okay, now its good to go

**Comment by utsavdotdev** [comment]
Merged 🚀

**Pull request merged**
