### PR TITLE
Improve site performance and optimization.

### PR DESCRIPTION
**Pull request by sarojregmi200**
This pull request tries to solve #18. And this will be updated gradually overtime as this will require some research to complete.

## **Todo:**
**Mobile:**
- [x] Improve Accessibility.
- [x] Improve Seo.
- [x] Improve Best Practices.
- [x] Improve Performance.

**Desktop:**
- [x] Improve Accessibility.
- [x] Improve Seo.
- [x] Improve Best Practices.
- [x] Improve Performance.

### CODE REVIEW

**Comment by sarojregmi200** [comment]
I have found and confirmed that the best practices score poor due to browser extension. And that it why it has a good score in mobile as there are no extension.(Speculation) Anyways it is already at 100% which is maximum amount of score that could be achieved.

**Comment by sarojregmi200** [comment]
I think this concludes it.
And Now the metrics are in acceptable state.


Image:
20240824_16h49m17s_grim

**Comment by utsavdotdev** [comment]
In mobile view, the home screen layout is broken, as shown in the attached screenshot. Additionally, on the main screen, the image quality appears unclear, and the layout isn't properly fixed. Could you please address these issues?
Screenshot 2024-08-24 at 18 16 11
Screenshot 2024-08-24 at 18 19 46

**Comment by sarojregmi200** [comment]
Ok will address it ASAP. My bad for not checking in mobile view properly.

**Comment by utsavdotdev** [comment]
No worries, The way you have done the optimization is top notch.

**Comment by sarojregmi200** [comment]
Done!! I have made it similar to the one that is already in deployment. Can you check if anything else is broken?

**Comment by utsavdotdev** [comment]
Fantastic work, @sarojregmi! Just one final tweak needed—fixing this will make your contribution truly outstanding. The issue is with the image.
Screenshot 2024-08-25 at 10 24 52

Once again, Thanks for the valuable contribution!

**Comment by sarojregmi200** [comment]
Can you please specify which image?

**Comment by utsavdotdev** [comment]
I mean to say the issue is reflected by below image

**Comment by sarojregmi200** [comment]
I see you mean I should also fix the button and the image overlapping? 

For sure.
I did not fix it earlier because I saw that the site had it that way.

**Comment by utsavdotdev** [comment]
Oh, ok!

**Comment by sarojregmi200** [comment]
I believe the issue with the image and the button responsiveness is now resolved? Is it good enough?

**Comment by utsavdotdev** [comment]
Yep, It is perfect to push in production. Thanks

**Pull request merged**
