### PR TITLE
Responsive Navbar

### PR DESCRIPTION
**Pull request by gmm-00**
I refined the Navbar to enhance responsiveness, improve accessibility, and simplify the structure. The updates ensure a cleaner codebase, better usability across devices, and a more polished user experience for both mobile and desktop views.

### CODE REVIEW

**Comment by utsavdotdev** [comment]
hi @gmm-00, Can you provide before and after preview of your changes?

**Comment by gmm-00** [comment]
> hi @gmm-00, Can you provide before and after preview of your changes?

**Comment by gmm-00** [comment]
> hi @gmm-00, Can you provide before and after preview of your changes?

Can i send you video?

**Comment by gmm-00** [comment]
Before:
https://github.com/user-attachments/assets/242127ed-62ad-4b8c-b9be-c0716e203274
After:
https://github.com/user-attachments/assets/cbaba0d1-fc80-4700-b06d-11b72c9053b4

**Comment by utsavdotdev** [comment]
hi @gmm-00, The required changes has been done. Thanks for your contribution in GNOME Nepal.

**Pull request merged**
