### PR TITLE
Bugfix/event section padding mobile

### PR DESCRIPTION
**Pull request by Aadithapa456**
## Changes

This PR solves #38 

-Replaced text with SVGs to improve responsiveness
- Changed padding of the parent of tab component from `p-1` to `px-1`

## Before Change: 
image

## After Change:
image

### CODE REVIEW

**Comment by utsavdotdev** [comment]
It seems there is a unupdated contributor list on your side. Have you pull latest changes from main branch

**Comment by Aadithapa456** [comment]
My forked repo was not synced, sorry for that. I fixed it

**Comment by utsavdotdev** [comment]
Congratulations on your @Aadithapa456 for contribution in GNOME Nepal.
Thanks for the PR

**Comment by Aadithapa456** [comment]
Thank you for your guidance @utsavdotdev

**Pull request merged**
