### PR TITLE
Add page not found handling with custom 404 error page

### PR DESCRIPTION
**Pull request by nayakOPS**
### **Description**:  
This pull request introduces a custom 404 error page that improves user experience when they navigate to non-existent routes on the site. When users visit an invalid URL, they will now see a clear message indicating that the page was not found. The page also includes a link to redirect them back to the home page.

### **Changes made**:
- Implemented a `NotFound.jsx` component for the custom 404 error page.
- Updated the routing logic to display the custom 404 error page for invalid routes.
- Styled the error page to make it user-friendly with a simple, clear message and a call-to-action button to return to the homepage.

### **Special notes**:
- **Route `/docs` behavior**: In previous versions of the code, the `/docs` route redirected users to a documentation page. With this update, navigating to `/docs` will now trigger the 404 error page, as the `/docs` page has not been implemented or is no longer part of the site. If the documentation feature is to be reintroduced, this route should be updated accordingly.
  
  Please note that the `/docs` route is considered a non-existent page in this update, and users will be directed to the 404 error page when trying to access it.

### CODE REVIEW

**Comment by utsavdotdev** [comment]
Hi @nayakOPS, the docs site is now fully set up and functional, though it still lacks some information. Since it's operational, this PR will be closed. Thanks for your concern

**Comment by nayakOPS** [comment]
Hi @utsavdotdev,

Thanks for your feedback. The goal of my update was to handle invalid URLs by rendering a custom 404 error page. My implementation uses hash-based routing (e.g., /#home works, and /#randomRoute shows the 404 page).

However, routes like /docs in the main repo use path-based routing, causing inconsistencies. I suggest standardizing all routes to path-based (e.g., /home, /about, /docs) to maintain consistency and ensure the 404 page works seamlessly across the site.

Let me know your thoughts!

**Comment by utsavdotdev** [comment]
You're right about your concern. The docs site is built using Docusaurus, so we need to route it through a proxy during local development and In production, It is handled by copying build files in one place. On your local system, is the docs site running at localhost:5173/docs? and Yeah I also missed setting up the 404 page. You can handle that, but make sure that when users are redirected to the /docs route, it displays the docs page correctly.

**Comment by utsavdotdev** [comment]
i got it. The proxy setup is missing on the your version. It is fixed in recent changes you can check it.

**Comment by utsavdotdev** [comment]
Merged 🚀

**Pull request merged**
