### PR TITLE
Maintained Dark Mode Compatibility enhancing ui 

### PR DESCRIPTION
**Pull request by abhishekpanthee**
Before --
before3
b2
before1
After -- 
Screenshot from 2024-10-05 11-05-54
Screenshot from 2024-10-05 11-05-50
Screenshot from 2024-10-05 11-05-41
Screenshot from 2024-10-05 11-05-37
Screenshot from 2024-10-05 11-05-31

### CODE REVIEW

**Comment by utsavdotdev** [comment]
Screenshot_2024-10-05-13-03-58-503_com android chrome

The subscribe button is not compatible with dark mode. Can you fix it?

**Comment by abhishekpanthee** [comment]
okay it was my idea for that styling despite of bg-covers i just  transitioned the text 
meaning if you write some text then the transition occurs 
if nothing is written it stays grey 
Screenshot from 2024-10-05 16-37-12
Screenshot from 2024-10-05 16-37-01
Screenshot from 2024-10-05 16-37-07

so is it a misunderstanding or there will be bg-cover needed please notify me 
also i have a request if possible please add hacktoberfest-accepted and hacktoberfest label in your repo

**Comment by utsavdotdev** [comment]
I have added the label. Could you set the button's background color to white in dark mode and black in light mode? Once that's done, it's ready to be merged

**Comment by abhishekpanthee** [comment]
yup did it also the white really didn't seem appealing so for light mode i used teal color hope you like it

**Comment by utsavdotdev** [comment]
Hi @abhishekpanthee , Teal color is not our standard color scheme. Please use the specified colors:

- In light mode, the button should be black with white text (default in light mode).
- In dark mode, the button should be white with black text.

**Comment by utsavdotdev** [comment]
Awesome work @abhishekpanthee, but there conflicting changes in the respective file.
Can you resolved it?
Screenshot_2024-10-06-14-16-58-227_com android chrome

**Pull request merged**
