### PR TITLE
ISSUE#39: Text overflow in contributions card 

### PR DESCRIPTION
**Pull request by syamjir**
Hi @utsavdotdev,

I have made changes to fix the text overflow issue in the contribution card for mobile screens. Please review the changes and provide your feedback.

Thank you!

### CODE REVIEW

**Comment by utsavdotdev** [comment]
Screenshot 2024-10-22 at 6 40 24 AM

The Contributor name is altering the width of the card? Can you resolve it?

**Comment by syamjir** [comment]
@utsavdotdev , Can i display one contributor at a time in mobile view, with left and right slide buttons to view other contributors

**Comment by utsavdotdev** [comment]
Yes, That will be perfect approach to fix this issue

**Comment by syamjir** [comment]
Hi@utsavdotdev, Added required changes; please review and provide feedback.
Thank you!

**Comment by utsavdotdev** [comment]
Great work @syamjir, Congratulation on your first contribution in GNOME Nepal.

**Comment by syamjir** [comment]
@utsavdotdev , Thank you! 😊 Excited to keep contributing and learning with GNOME Nepal!

**Pull request merged**
