### PR TITLE
partial fix for issue #21

### PR DESCRIPTION
**Pull request by sudanchapagain**
Everything related to text and image has been fixed. However, the sub-heading is a SVG element as such i have not dealt with it. The hierarchy issue too has not been fixed as design is out of my scope.

### CODE REVIEW

**Comment by utsavdotdev** [comment]
Great job @sudanchapagain! I can share the Figma design file with you. If you could complete the remaining work, it would be the cherry on top. 

Here’s the design link: [Figma Design](https://www.figma.com/design/r29pVQrxM2EKngcji2Euxc/Gnome-Nepal-Website-design?node-id=0-1&t=FbN9KoglcIbO3F7A-1).

**Comment by sudanchapagain** [comment]
Sure. will look into this sometime later.

**Comment by utsavdotdev** [comment]
Ok No worries, Good night

**Comment by sudanchapagain** [comment]
That's all that i will be doing, the hierarchy issue is not fix-able by me. I see no other option than redoing the whole text block or design of the whole page.

**Pull request merged**
